# Generated by Django 6.0.1 on 2026-02-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('lat', models.FloatField(default=10.7769, verbose_name='Vĩ độ')),
                ('lon', models.FloatField(default=106.7009, verbose_name='Kinh độ')),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Danh sách cửa hàng',
            },
        ),
    ]
