# Generated by Django 6.0.3 on 2026-03-27 05:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuaHang",
            fields=[
                (
                    "MaCH",
                    models.CharField(
                        db_column="mach",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "Loai",
                    models.CharField(
                        choices=[
                            ("Tiện Lợi", "Tiện Lợi"),
                            ("Gia Dụng", "Gia Dụng"),
                            ("Điện Tử", "Điện Tử"),
                        ],
                        db_column="loai",
                        max_length=50,
                    ),
                ),
                (
                    "Icon",
                    models.CharField(
                        blank=True, db_column="icon", max_length=20, null=True
                    ),
                ),
                ("DiaChi", models.TextField(blank=True, db_column="diachi", null=True)),
                (
                    "SDT",
                    models.CharField(
                        blank=True, db_column="sdt", max_length=20, null=True
                    ),
                ),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[
                            ("Hoạt động", "Hoạt động"),
                            ("Tạm ngưng", "Tạm ngưng"),
                            ("Vô hiệu hóa", "Vô hiệu hóa"),
                        ],
                        db_column="trangthai",
                        max_length=50,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        db_column="geom", srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Danh sách cửa hàng",
                "db_table": "cuahang",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                (
                    "MaDM",
                    models.CharField(
                        db_column="madm",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="tendm", max_length=255)),
                ("MoTa", models.TextField(blank=True, db_column="mota", null=True)),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh sách danh mục",
                "db_table": "danhmuc",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Kho",
            fields=[
                (
                    "MaKho",
                    models.CharField(
                        db_column="makho",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "Loai",
                    models.CharField(
                        choices=[
                            ("Kho Tổng", "Kho Tổng"),
                            ("Kho Chi Nhánh", "Kho Chi Nhánh"),
                        ],
                        db_column="loai",
                        max_length=50,
                    ),
                ),
                ("DiaChi", models.TextField(blank=True, db_column="diachi", null=True)),
                (
                    "Icon",
                    models.CharField(
                        blank=True, db_column="icon", max_length=20, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        db_column="geom", srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Kho",
                "verbose_name_plural": "Danh sách kho",
                "db_table": "kho",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "MaNV",
                    models.CharField(
                        db_column="manv",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "SDT",
                    models.CharField(
                        blank=True, db_column="sdt", max_length=20, null=True
                    ),
                ),
                ("MatKhau", models.TextField(db_column="matkhau")),
                (
                    "Role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Nhân Viên", "Nhân Viên"),
                            ("Kế Toán", "Kế Toán"),
                        ],
                        db_column="role",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Danh sách nhân viên",
                "db_table": "nhanvien",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên cửa hàng")),
                ("address", models.CharField(max_length=255, verbose_name="Địa chỉ")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                ("lat", models.FloatField(default=10.7769, verbose_name="Vĩ độ")),
                ("lon", models.FloatField(default=106.7009, verbose_name="Kinh độ")),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Danh sách cửa hàng",
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "MaSP",
                    models.CharField(
                        db_column="masp",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "Image",
                    models.ImageField(
                        blank=True, db_column="image", null=True, upload_to="products/"
                    ),
                ),
                ("MieuTa", models.TextField(blank=True, db_column="mieuta", null=True)),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[("Đang bán", "Đang bán"), ("Ngừng bán", "Ngừng bán")],
                        db_column="trangthai",
                        max_length=50,
                    ),
                ),
                (
                    "DanhMuc",
                    models.ForeignKey(
                        blank=True,
                        db_column="danhmuc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="MyApp.danhmuc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Danh sách sản phẩm",
                "db_table": "sanpham",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="YeuCauNhapKho",
            fields=[
                (
                    "MaYC",
                    models.CharField(
                        db_column="mayc",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ngay", models.DateField(db_column="ngay")),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[("Chờ duyệt", "Chờ duyệt"), ("Đã duyệt", "Đã duyệt")],
                        db_column="trangthai",
                        max_length=50,
                    ),
                ),
                ("GhiChu", models.TextField(blank=True, db_column="ghichu", null=True)),
                (
                    "MaNV",
                    models.ForeignKey(
                        blank=True,
                        db_column="manv",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.nhanvien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu nhập kho",
                "verbose_name_plural": "Danh sách yêu cầu nhập kho",
                "db_table": "yeucaunhapkho",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PhanBoCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "khoang_cach",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("thoi_gian", models.IntegerField(blank=True, null=True)),
                ("uu_tien", models.IntegerField()),
                (
                    "cua_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MyApp.cuahang"
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MyApp.kho"
                    ),
                ),
            ],
            options={
                "unique_together": {("cua_hang", "kho")},
            },
        ),
        migrations.CreateModel(
            name="HangTonKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField(db_column="soluong")),
                (
                    "MaKho",
                    models.ForeignKey(
                        db_column="makho",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.kho",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        db_column="masp",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.sanpham",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hàng tồn kho",
                "verbose_name_plural": "Danh sách hàng tồn kho",
                "db_table": "hangtonkho",
                "managed": True,
                "unique_together": {("MaKho", "MaSP")},
            },
        ),
        migrations.CreateModel(
            name="NhapKhoChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField(db_column="soluong")),
                (
                    "MaKho",
                    models.ForeignKey(
                        db_column="makho",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.kho",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        db_column="masp",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.sanpham",
                    ),
                ),
                (
                    "MaYC",
                    models.ForeignKey(
                        db_column="mayc",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.yeucaunhapkho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhập kho chi tiết",
                "verbose_name_plural": "Chi tiết nhập kho",
                "db_table": "nhapkhochitiet",
                "managed": True,
                "unique_together": {("MaYC", "MaKho", "MaSP")},
            },
        ),
    ]
