# Generated by Django 6.0.2 on 2026-05-03 13:10

import ckeditor.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.PositiveIntegerField(db_column="soluong")),
                (
                    "GiaBan",
                    models.DecimalField(
                        db_column="giaban", decimal_places=0, max_digits=12
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn hàng",
                "verbose_name_plural": "Chi tiết các đơn hàng",
                "db_table": "chitietdonhang",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChiTietGioHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SoLuong",
                    models.PositiveIntegerField(db_column="soluong", default=1),
                ),
            ],
            options={
                "verbose_name": "Chi tiết giỏ hàng",
                "verbose_name_plural": "Chi tiết các giỏ hàng",
                "db_table": "chitietgiohang",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CuaHang",
            fields=[
                (
                    "MaCH",
                    models.CharField(
                        db_column="mach",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "Loai",
                    models.CharField(
                        choices=[
                            ("Tiện Lợi", "Tiện Lợi"),
                            ("Gia Dụng", "Gia Dụng"),
                            ("Điện Tử", "Điện Tử"),
                        ],
                        db_column="loai",
                        max_length=50,
                    ),
                ),
                (
                    "Icon",
                    models.CharField(
                        blank=True, db_column="icon", max_length=20, null=True
                    ),
                ),
                ("DiaChi", models.TextField(blank=True, db_column="diachi", null=True)),
                (
                    "SDT",
                    models.CharField(
                        blank=True, db_column="sdt", max_length=20, null=True
                    ),
                ),
                (
                    "hinhanh",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        db_column="hinhanh",
                        null=True,
                    ),
                ),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[
                            ("Hoạt động", "Hoạt động"),
                            ("Tạm ngưng", "Tạm ngưng"),
                            ("Vô hiệu hóa", "Vô hiệu hóa"),
                        ],
                        db_column="trangthai",
                        max_length=50,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        db_column="geom", srid=4326
                    ),
                ),
                (
                    "GioMoCua",
                    models.TimeField(
                        blank=True,
                        db_column="giomocua",
                        null=True,
                        verbose_name="Giờ mở cửa",
                    ),
                ),
                (
                    "GioDongCua",
                    models.TimeField(
                        blank=True,
                        db_column="giodongcua",
                        null=True,
                        verbose_name="Giờ đóng cửa",
                    ),
                ),
                (
                    "MoTa",
                    ckeditor.fields.RichTextField(
                        blank=True, db_column="mota", null=True, verbose_name="Mô tả"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Danh sách cửa hàng",
                "db_table": "cuahang",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NguoiDung", models.CharField(db_column="nguoidung", max_length=255)),
                ("Diem", models.IntegerField(db_column="diem")),
                ("BinhLuan", models.TextField(db_column="binhluan")),
                (
                    "NgayTao",
                    models.DateTimeField(auto_now_add=True, db_column="ngaytao"),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Danh sách đánh giá",
                "db_table": "danhgia",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DanhGiaCuaHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SoSao",
                    models.IntegerField(
                        db_column="sosao",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Số sao",
                    ),
                ),
                (
                    "NhanXet",
                    models.TextField(
                        blank=True,
                        db_column="nhanxet",
                        null=True,
                        verbose_name="Nhận xét",
                    ),
                ),
                (
                    "NgayTao",
                    models.DateTimeField(auto_now_add=True, db_column="ngaytao"),
                ),
            ],
            options={
                "verbose_name": "Đánh giá cửa hàng",
                "verbose_name_plural": "Danh sách đánh giá cửa hàng",
                "db_table": "danhgiacuahang",
                "ordering": ["-NgayTao"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                (
                    "MaDM",
                    models.CharField(
                        db_column="madm",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="tendm", max_length=255)),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh sách danh mục",
                "db_table": "danhmuc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DonHang",
            fields=[
                (
                    "NgayTao",
                    models.DateTimeField(auto_now_add=True, db_column="ngaytao"),
                ),
                (
                    "MaDH",
                    models.CharField(
                        db_column="madh",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "TenNguoiNhan",
                    models.CharField(db_column="tennguoinhan", max_length=255),
                ),
                ("SDT_Nhan", models.CharField(db_column="sdt_nhan", max_length=20)),
                ("DiaChi_Nhan", models.TextField(db_column="diachi_nhan")),
                (
                    "TongTien",
                    models.DecimalField(
                        db_column="tongtien", decimal_places=0, max_digits=15
                    ),
                ),
                (
                    "PhuongThucThanhToan",
                    models.CharField(
                        choices=[
                            ("COD", "Thanh toán khi nhận hàng"),
                            ("MoMo", "Ví điện tử MoMo"),
                            ("Bank", "Chuyển khoản Ngân hàng"),
                        ],
                        db_column="pt_thanhtoan",
                        default="COD",
                        max_length=50,
                    ),
                ),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[
                            ("Đang xử lý", "Đang xử lý"),
                            ("Đang giao", "Đang giao"),
                            ("Đã hoàn thành", "Đã hoàn thành"),
                            ("Đã hủy", "Đã hủy"),
                            ("Đã trả hàng", "Đã trả hàng"),
                        ],
                        db_column="trangthai",
                        default="Đang xử lý",
                        max_length=50,
                    ),
                ),
                ("GhiChu", models.TextField(blank=True, db_column="ghichu", null=True)),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Danh sách đơn hàng",
                "db_table": "donhang",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GioHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SessionID",
                    models.CharField(
                        blank=True, db_column="session_id", max_length=255, null=True
                    ),
                ),
                (
                    "NgayTao",
                    models.DateTimeField(auto_now_add=True, db_column="ngaytao"),
                ),
                (
                    "NgayCapNhat",
                    models.DateTimeField(auto_now=True, db_column="ngaycapnhat"),
                ),
            ],
            options={
                "verbose_name": "Giỏ hàng",
                "verbose_name_plural": "Danh sách giỏ hàng",
                "db_table": "giohang",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HangTonKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField(db_column="soluong")),
            ],
            options={
                "verbose_name": "Hàng tồn kho",
                "verbose_name_plural": "Danh sách hàng tồn kho",
                "db_table": "hangtonkho",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Kho",
            fields=[
                (
                    "MaKho",
                    models.CharField(
                        db_column="makho",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "Loai",
                    models.CharField(
                        choices=[
                            ("Kho Tổng", "Kho Tổng"),
                            ("Kho Chi Nhánh", "Kho Chi Nhánh"),
                        ],
                        db_column="loai",
                        max_length=50,
                    ),
                ),
                ("DiaChi", models.TextField(blank=True, db_column="diachi", null=True)),
                (
                    "Icon",
                    models.CharField(
                        blank=True, db_column="icon", max_length=20, null=True
                    ),
                ),
                (
                    "hinhanh",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        db_column="hinhanh",
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        db_column="geom", srid=4326
                    ),
                ),
                (
                    "MoTa",
                    ckeditor.fields.RichTextField(
                        blank=True, db_column="mota", null=True, verbose_name="Mô tả"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kho",
                "verbose_name_plural": "Danh sách kho",
                "db_table": "kho",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "MaNV",
                    models.CharField(
                        db_column="manv",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "SDT",
                    models.CharField(
                        blank=True, db_column="sdt", max_length=20, null=True
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True, db_column="email", max_length=255, null=True
                    ),
                ),
                ("MatKhau", models.TextField(db_column="matkhau")),
                (
                    "Role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Nhân Viên", "Nhân Viên"),
                            ("Kế Toán", "Kế Toán"),
                            ("User", "User"),
                        ],
                        db_column="role",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Danh sách nhân viên",
                "db_table": "nhanvien",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NhapKhoChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.IntegerField(db_column="soluong")),
            ],
            options={
                "verbose_name": "Nhập kho chi tiết",
                "verbose_name_plural": "Chi tiết nhập kho",
                "db_table": "nhapkhochitiet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "MaSP",
                    models.CharField(
                        db_column="masp",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ten", models.CharField(db_column="ten", max_length=255)),
                (
                    "Image",
                    models.ImageField(
                        blank=True,
                        db_column="image",
                        max_length=255,
                        null=True,
                        upload_to="products/",
                    ),
                ),
                ("MieuTa", models.TextField(blank=True, db_column="mieuta", null=True)),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[("Đang bán", "Đang bán"), ("Ngừng bán", "Ngừng bán")],
                        db_column="trangthai",
                        max_length=50,
                    ),
                ),
                (
                    "Gia",
                    models.DecimalField(
                        db_column="gia",
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Giá bán",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Danh sách sản phẩm",
                "db_table": "sanpham",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="XuatKhoChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.PositiveIntegerField(db_column="soluong")),
            ],
            options={
                "verbose_name": "Xuất kho chi tiết",
                "verbose_name_plural": "Chi tiết xuất kho",
                "db_table": "xuatkhochitiet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YeuCauNhapKho",
            fields=[
                (
                    "MaYC",
                    models.CharField(
                        db_column="mayc",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Ngay", models.DateField(db_column="ngay")),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[("Chờ duyệt", "Chờ duyệt"), ("Đã duyệt", "Đã duyệt")],
                        db_column="trangthai",
                        max_length=50,
                    ),
                ),
                ("GhiChu", models.TextField(blank=True, db_column="ghichu", null=True)),
            ],
            options={
                "verbose_name": "Yêu cầu nhập kho",
                "verbose_name_plural": "Danh sách yêu cầu nhập kho",
                "db_table": "yeucaunhapkho",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YeuCauTraHang",
            fields=[
                (
                    "MaYCTH",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Mã yêu cầu",
                    ),
                ),
                (
                    "SdtLienHe",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại liên hệ",
                    ),
                ),
                (
                    "EmailLienHe",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email liên hệ",
                    ),
                ),
                (
                    "SoTaiKhoanNH",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Số tài khoản ngân hàng",
                    ),
                ),
                (
                    "SoTaiKhoanMoMo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Số tài khoản MoMo",
                    ),
                ),
                ("LyDo", models.TextField(verbose_name="Lý do trả hàng")),
                (
                    "AnhHoaDon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="returns/invoices/",
                        verbose_name="Ảnh hóa đơn",
                    ),
                ),
                (
                    "AnhMinhChung",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="returns/proof/",
                        verbose_name="Ảnh minh chứng",
                    ),
                ),
                (
                    "GhiChuAdmin",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú của Admin"
                    ),
                ),
                (
                    "SoTienHoan",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Số tiền hoàn lại",
                    ),
                ),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đang xử lý", "Đang xử lý"),
                            ("Đã hoàn tiền", "Đã hoàn tiền"),
                            ("Từ chối", "Từ chối"),
                        ],
                        default="Mới",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "NgayTao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày yêu cầu"
                    ),
                ),
                (
                    "NgayXuLy",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày xử lý"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu trả hàng",
                "verbose_name_plural": "Các yêu cầu trả hàng",
                "db_table": "yeucautrahang",
                "ordering": ["-NgayTao"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YeuCauXuatKho",
            fields=[
                (
                    "MaPX",
                    models.CharField(
                        db_column="mapx",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Mã phiếu xuất",
                    ),
                ),
                (
                    "Ngay",
                    models.DateField(
                        auto_now_add=True, db_column="ngay", verbose_name="Ngày xuất"
                    ),
                ),
                (
                    "LyDo",
                    models.CharField(
                        choices=[
                            ("Bán hàng", "Bán hàng"),
                            ("Trả hàng nhà cung cấp", "Trả hàng nhà cung cấp"),
                            ("Hàng hỏng", "Hàng hỏng"),
                            ("Chuyển kho", "Chuyển kho"),
                            ("Khác", "Khác"),
                        ],
                        db_column="lydo",
                        default="Bán hàng",
                        max_length=50,
                        verbose_name="Lý do xuất",
                    ),
                ),
                (
                    "TrangThai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã xuất", "Đã xuất"),
                            ("Đã hủy", "Đã hủy"),
                        ],
                        db_column="trangthai",
                        default="Mới",
                        max_length=50,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "GhiChu",
                    models.TextField(
                        blank=True,
                        db_column="ghichu",
                        null=True,
                        verbose_name="Ghi chú",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu xuất kho",
                "verbose_name_plural": "Danh sách yêu cầu xuất kho",
                "db_table": "yeucauxuatkho",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên cửa hàng")),
                ("address", models.CharField(max_length=255, verbose_name="Địa chỉ")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                ("lat", models.FloatField(default=10.7769, verbose_name="Vĩ độ")),
                ("lon", models.FloatField(default=106.7009, verbose_name="Kinh độ")),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Danh sách cửa hàng",
            },
        ),
        migrations.CreateModel(
            name="PhanBoCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "khoang_cach",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("thoi_gian", models.IntegerField(blank=True, null=True)),
                ("uu_tien", models.IntegerField()),
                (
                    "cua_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MyApp.cuahang"
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MyApp.kho"
                    ),
                ),
            ],
            options={
                "unique_together": {("cua_hang", "kho")},
            },
        ),
    ]
