# Generated by Django 6.0.1 on 2026-02-04 12:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('MaCH', models.CharField(db_column='mach', max_length=20, primary_key=True, serialize=False)),
                ('Ten', models.CharField(db_column='ten', max_length=255)),
                ('Loai', models.CharField(blank=True, db_column='loai', max_length=50, null=True)),
                ('Icon', models.CharField(blank=True, db_column='icon', max_length=20, null=True)),
                ('DiaChi', models.TextField(blank=True, db_column='diachi', null=True)),
                ('SDT', models.CharField(blank=True, db_column='sdt', max_length=20, null=True)),
                ('TrangThai', models.CharField(blank=True, db_column='trangthai', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326)),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Danh sách cửa hàng',
                'db_table': 'cuahang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HangTonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(db_column='soluong')),
            ],
            options={
                'verbose_name': 'Hàng tồn kho',
                'verbose_name_plural': 'Danh sách hàng tồn kho',
                'db_table': 'hangtonkho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('MaKho', models.CharField(db_column='makho', max_length=20, primary_key=True, serialize=False)),
                ('Ten', models.CharField(db_column='ten', max_length=255)),
                ('Loai', models.CharField(blank=True, db_column='loai', max_length=50, null=True)),
                ('DiaChi', models.TextField(blank=True, db_column='diachi', null=True)),
                ('Icon', models.CharField(blank=True, db_column='icon', max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326)),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Danh sách kho',
                'db_table': 'kho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(db_column='manv', max_length=20, primary_key=True, serialize=False)),
                ('Ten', models.CharField(db_column='ten', max_length=255)),
                ('SDT', models.CharField(blank=True, db_column='sdt', max_length=20, null=True)),
                ('MatKhau', models.TextField(db_column='matkhau')),
                ('Role', models.CharField(blank=True, db_column='role', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhapKhoChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(db_column='soluong')),
            ],
            options={
                'verbose_name': 'Nhập kho chi tiết',
                'verbose_name_plural': 'Chi tiết nhập kho',
                'db_table': 'nhapkhochitiet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(db_column='masp', max_length=20, primary_key=True, serialize=False)),
                ('Ten', models.CharField(db_column='ten', max_length=255)),
                ('Image', models.CharField(blank=True, db_column='image', max_length=20, null=True)),
                ('DanhMuc', models.CharField(blank=True, db_column='danhmuc', max_length=100, null=True)),
                ('MieuTa', models.TextField(blank=True, db_column='mieuta', null=True)),
                ('TrangThai', models.CharField(blank=True, db_column='trangthai', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
                'db_table': 'sanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YeuCauNhapKho',
            fields=[
                ('MaYC', models.CharField(db_column='mayc', max_length=20, primary_key=True, serialize=False)),
                ('Ngay', models.DateField(db_column='ngay')),
                ('TrangThai', models.CharField(blank=True, db_column='trangthai', max_length=50, null=True)),
                ('GhiChu', models.TextField(blank=True, db_column='ghichu', null=True)),
            ],
            options={
                'verbose_name': 'Yêu cầu nhập kho',
                'verbose_name_plural': 'Danh sách yêu cầu nhập kho',
                'db_table': 'yeucaunhapkho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('TongTien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('TrangThai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_giao', 'Đang giao'), ('da_hoan_thanh', 'Đã hoàn thành'), ('da_huy', 'Đã hủy')], default='cho_xu_ly', max_length=20)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=255)),
                ('SDT', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('DiaChi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách khách hàng',
            },
        ),
        migrations.CreateModel(
            name='GiaoHang',
            fields=[
                ('MaGH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NguoiGiao', models.CharField(max_length=255)),
                ('SdtNguoiGiao', models.CharField(max_length=20)),
                ('NgayGiao', models.DateTimeField(blank=True, null=True)),
                ('TrangThai', models.CharField(default='Đang chuẩn bị', max_length=50)),
                ('DonHang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyApp.donhang')),
            ],
            options={
                'verbose_name': 'Giao hàng',
                'verbose_name_plural': 'Danh sách giao hàng',
            },
        ),
        migrations.AddField(
            model_name='donhang',
            name='KhachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.khachhang'),
        ),
    ]
