# Generated by Django 6.0.3 on 2026-04-01 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuahang",
            name="hinhanh",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                db_column="hinhanh",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kho",
            name="hinhanh",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                db_column="hinhanh",
                null=True,
            ),
        ),
    ]
