# Generated by Django 6.0.3 on 2026-04-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donhang",
            name="NgayTao",
            field=models.DateTimeField(
                auto_now_add=True, db_column="ngaytao", null=True
            ),
        ),
    ]
