# Generated by Django 6.0.2 on 2026-02-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_cuahang_hangtonkho_kho_nhanvien_nhapkhochitiet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDM', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=255)),
                ('MoTa', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh sách danh mục',
            },
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='KhachHang',
        ),
        migrations.RemoveField(
            model_name='giaohang',
            name='DonHang',
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.DeleteModel(
            name='DonHang',
        ),
        migrations.DeleteModel(
            name='GiaoHang',
        ),
    ]
