# Generated by Django 6.0.3 on 2026-04-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0002_cuahang_hinhanh_kho_hinhanh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="Image",
            field=models.ImageField(
                blank=True,
                db_column="image",
                max_length=255,
                null=True,
                upload_to="products/",
            ),
        ),
    ]
