# Generated by Django 6.0.3 on 2026-04-13 18:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0003_alter_sanpham_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="danhmuc",
            name="MoTa",
        ),
        migrations.AddField(
            model_name="cuahang",
            name="MoTa",
            field=ckeditor.fields.RichTextField(
                blank=True, db_column="mota", null=True, verbose_name="Mô tả"
            ),
        ),
        migrations.AddField(
            model_name="kho",
            name="MoTa",
            field=ckeditor.fields.RichTextField(
                blank=True, db_column="mota", null=True, verbose_name="Mô tả"
            ),
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="Email",
            field=models.EmailField(
                blank=True, db_column="email", max_length=255, null=True
            ),
        ),
    ]
