# Generated by Django 6.0.1 on 2026-03-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_danhmuc_remove_donhang_khachhang_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhmuc',
            options={'managed': False, 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh sách danh mục'},
        ),
        migrations.CreateModel(
            name='PhanBoCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoang_cach', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('thoi_gian', models.IntegerField(blank=True, null=True)),
                ('uu_tien', models.IntegerField()),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.cuahang')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.kho')),
            ],
            options={
                'unique_together': {('cua_hang', 'kho')},
            },
        ),
    ]
