# Generated by Django 6.0.1 on 2026-03-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_danhmuc_options_phanbocungcap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='danhmuc',
            table='danhmuc',
        ),
    ]
