# Generated by Django 6.0.3 on 2026-04-13 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0004_remove_danhmuc_mota_cuahang_mota_kho_mota_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhGiaCuaHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SoSao",
                    models.IntegerField(
                        db_column="sosao",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Số sao",
                    ),
                ),
                (
                    "NhanXet",
                    models.TextField(
                        blank=True,
                        db_column="nhanxet",
                        null=True,
                        verbose_name="Nhận xét",
                    ),
                ),
                (
                    "NgayTao",
                    models.DateTimeField(auto_now_add=True, db_column="ngaytao"),
                ),
                (
                    "CuaHang",
                    models.ForeignKey(
                        db_column="mach",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_gia",
                        to="MyApp.cuahang",
                    ),
                ),
                (
                    "NhanVien",
                    models.ForeignKey(
                        db_column="manv",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyApp.nhanvien",
                    ),
                ),
            ],
            options={
                "db_table": "danhgiacuahang",
                "ordering": ["-NgayTao"],
                "managed": True,
            },
        ),
    ]
